name: Gradle Pipeline

on:
  push:
    branches: [ "main" ]
    tags: [ "v**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@v2.9.0
        with:
          dependency-graph: generate-and-submit
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Docker image
        if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
        run: ./gradlew bootBuildImage -PpublishImage
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
